class JuzBoundary {
  const JuzBoundary({
    required this.juzNumber,
    required this.startSurahId,
    required this.startAyah,
    required this.endSurahId,
    required this.endAyah,
  });

  final int juzNumber;
  final int startSurahId;
  final int startAyah;
  final int endSurahId;
  final int endAyah;
}

const List<JuzBoundary> kJuzBoundaries = <JuzBoundary>[
  JuzBoundary(
    juzNumber: 1,
    startSurahId: 1,
    startAyah: 1,
    endSurahId: 2,
    endAyah: 141,
  ),
  JuzBoundary(
    juzNumber: 2,
    startSurahId: 2,
    startAyah: 142,
    endSurahId: 2,
    endAyah: 252,
  ),
  JuzBoundary(
    juzNumber: 3,
    startSurahId: 2,
    startAyah: 253,
    endSurahId: 3,
    endAyah: 92,
  ),
  JuzBoundary(
    juzNumber: 4,
    startSurahId: 3,
    startAyah: 93,
    endSurahId: 4,
    endAyah: 23,
  ),
  JuzBoundary(
    juzNumber: 5,
    startSurahId: 4,
    startAyah: 24,
    endSurahId: 4,
    endAyah: 147,
  ),
  JuzBoundary(
    juzNumber: 6,
    startSurahId: 4,
    startAyah: 148,
    endSurahId: 5,
    endAyah: 81,
  ),
  JuzBoundary(
    juzNumber: 7,
    startSurahId: 5,
    startAyah: 82,
    endSurahId: 6,
    endAyah: 110,
  ),
  JuzBoundary(
    juzNumber: 8,
    startSurahId: 6,
    startAyah: 111,
    endSurahId: 7,
    endAyah: 87,
  ),
  JuzBoundary(
    juzNumber: 9,
    startSurahId: 7,
    startAyah: 88,
    endSurahId: 8,
    endAyah: 40,
  ),
  JuzBoundary(
    juzNumber: 10,
    startSurahId: 8,
    startAyah: 41,
    endSurahId: 9,
    endAyah: 92,
  ),
  JuzBoundary(
    juzNumber: 11,
    startSurahId: 9,
    startAyah: 93,
    endSurahId: 11,
    endAyah: 5,
  ),
  JuzBoundary(
    juzNumber: 12,
    startSurahId: 11,
    startAyah: 6,
    endSurahId: 12,
    endAyah: 52,
  ),
  JuzBoundary(
    juzNumber: 13,
    startSurahId: 12,
    startAyah: 53,
    endSurahId: 14,
    endAyah: 52,
  ),
  JuzBoundary(
    juzNumber: 14,
    startSurahId: 15,
    startAyah: 1,
    endSurahId: 16,
    endAyah: 128,
  ),
  JuzBoundary(
    juzNumber: 15,
    startSurahId: 17,
    startAyah: 1,
    endSurahId: 18,
    endAyah: 74,
  ),
  JuzBoundary(
    juzNumber: 16,
    startSurahId: 18,
    startAyah: 75,
    endSurahId: 20,
    endAyah: 135,
  ),
  JuzBoundary(
    juzNumber: 17,
    startSurahId: 21,
    startAyah: 1,
    endSurahId: 22,
    endAyah: 78,
  ),
  JuzBoundary(
    juzNumber: 18,
    startSurahId: 23,
    startAyah: 1,
    endSurahId: 25,
    endAyah: 20,
  ),
  JuzBoundary(
    juzNumber: 19,
    startSurahId: 25,
    startAyah: 21,
    endSurahId: 27,
    endAyah: 55,
  ),
  JuzBoundary(
    juzNumber: 20,
    startSurahId: 27,
    startAyah: 56,
    endSurahId: 29,
    endAyah: 45,
  ),
  JuzBoundary(
    juzNumber: 21,
    startSurahId: 29,
    startAyah: 46,
    endSurahId: 33,
    endAyah: 30,
  ),
  JuzBoundary(
    juzNumber: 22,
    startSurahId: 33,
    startAyah: 31,
    endSurahId: 36,
    endAyah: 27,
  ),
  JuzBoundary(
    juzNumber: 23,
    startSurahId: 36,
    startAyah: 28,
    endSurahId: 39,
    endAyah: 31,
  ),
  JuzBoundary(
    juzNumber: 24,
    startSurahId: 39,
    startAyah: 32,
    endSurahId: 41,
    endAyah: 46,
  ),
  JuzBoundary(
    juzNumber: 25,
    startSurahId: 41,
    startAyah: 47,
    endSurahId: 45,
    endAyah: 37,
  ),
  JuzBoundary(
    juzNumber: 26,
    startSurahId: 46,
    startAyah: 1,
    endSurahId: 51,
    endAyah: 30,
  ),
  JuzBoundary(
    juzNumber: 27,
    startSurahId: 51,
    startAyah: 31,
    endSurahId: 57,
    endAyah: 29,
  ),
  JuzBoundary(
    juzNumber: 28,
    startSurahId: 58,
    startAyah: 1,
    endSurahId: 66,
    endAyah: 12,
  ),
  JuzBoundary(
    juzNumber: 29,
    startSurahId: 67,
    startAyah: 1,
    endSurahId: 77,
    endAyah: 50,
  ),
  JuzBoundary(
    juzNumber: 30,
    startSurahId: 78,
    startAyah: 1,
    endSurahId: 114,
    endAyah: 6,
  ),
];
